import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

import Header from "../components/Header";
import Nav from "../components/Nav";
import MidSection from "../components/MidSection";
import LastSection from "../components/LastSection";
import Slider from "../components/Slider";
import Footer from "../components/Footer";

export default function Home() {
  // const [state, setState] = useState(0);
  // console.log("test");

  // useEffect(() => {
  //   setState(1);
  // }, []);
  return (
    <main>
      <Head>
        <title>FlightApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <MidSection />
      <LastSection />
      <Slider />
      <Footer />
    </main>
  );
}
